export class soundSrc {
  static system = {
    systemBack: './sound/systemBack.wav',
    systemBuzzer: './sound/systemBuzzer.wav',
    systemCursor: './sound/systemCursor.wav',
    systemEnter: './sound/systemEnter.ogg',
    systemSelect: './sound/systemSelect.wav',
    systemScore: './sound/systemScore.wav',
    systemLevelUp: './sound/systemLevelUp.wav',
    systemPause: './sound/systemPause.wav',
    systemRoundClear: './sound/systemRoundClear.ogg',
    systemGameOver: './sound/systemGameOver.ogg',
    systemPlayerDamage: './sound/systemPlayerDamage.wav',
    systemPlayerDamageBig: './sound/systemPlayerDamageBig.wav',
    systemPlayerDamageDanger: './sound/systemPlayerDamageDanger.wav',
    systemPlayerDie: './sound/systemPlayerDie.ogg',
    systemSkillSelect: './sound/systemSkillSelect.wav',
  }

  static skill = {
    // baseSkill total count 20
    skillMultyshotUse: './sound/skillMultyshotUse.wav',
    skillMultyshotShot: './sound/skillMultyshotShot.wav',
    skillMissileShot: './sound/skillMissileShot.wav',
    skillMissileHit: './sound/skillMissileHit.wav',
    skillArrowShot: './sound/skillArrow.wav',
    skillLaserShot: './sound/skillLaserShot.ogg',
    skillSapiaWeapon: './sound/skillSapiaWeapon.ogg',
    skillParapoHit: './sound/skillParapoHit.wav',
    skillBlasterShot: './sound/skillBlasterShot.ogg',
    skillSidewaveShot: './sound/skillSidewaveShot.wav',
    skillCriticalChaser: './sound/skillCriticalChaser.ogg',
    skillCriticalChaserHit: './sound/skillCriticalChaserHit.ogg',
    skillHyperBall: './sound/skillHyperBall.wav',
    skillPileBunker: './sound/skillPileBunker.ogg',
    skillPileBunkerHit2: './sound/skillPileBunkerHit2.wav',
    skillPileBunkerHit3: './sound/skillPileBunkerHit3.wav',
    skillSword: './sound/skillSword.ogg',
    skillSwordHit: './sound/skillSwordHit.wav',
    skillSantansu: './sound/skillSantansuHit.ogg',
    skillWhiteflash: './sound/skillWhiteflash.ogg',
    skillRapid: './sound/skillRapid.wav',
    skillSeondanil: './sound/skillSeondanil.ogg',
    skillSeondanilHit: './sound/skillSeondanilHit.wav',
    skillRing: './sound/skillRing.wav',
    skillBoomerang: './sound/skillBoomerang.ogg',
    skillHanjumeok: './sound/skillHanjumeok.ogg',
    skillHanjumeokHit: './sound/skillHanjumeokHit.wav',
    skillHanjumeokSplash: './sound/skillHanjumeokSplash.ogg',
    skillMoon: './sound/skillMoon.ogg',
    skillMoonAttack: './sound/skillMoonAttack.ogg',
  }

  static enemyDie = {
    enemyDieMeteorite1: './sound/enemyDieMeteorite1.wav',
    enemyDieMeteorite2: './sound/enemyDieMeteorite2.wav',
    enemyDieMeteorite3: './sound/enemyDieMeteorite3.wav',
    enemyDieMeteorite4: './sound/enemyDieMeteorite4.wav',
    enemyDieMeteorite5: './sound/enemyDieMeteorite5.wav',
    enemyDieMeteoriteBomb: './sound/enemyDieMeteoriteBomb.wav',
    enemyDieMetoriteRed: './sound/enemyDieMeteoriteRed.wav',
    enemyDieSpaceCar: './sound/enemyDieSpaceCar.wav',
    enemyDieSpaceComet: './sound/enemyDieSpaceComet.wav',
    enemyDieSpaceEnergy: './sound/enemyDieSpaceEnergy.wav',
    enemyDieSpaceGamjigi: './sound/enemyDieSpaceGamjigi.wav',
    enemyDieSpaceLight: './sound/enemyDieSpaceLight.wav',
    enemyDieSpaceRocket: './sound/enemyDieSpaceRocket.wav',
    enemyDieSpaceSmall: './sound/enemyDieSpaceSmall.wav',
    enemyDieSpaceSquare: './sound/enemyDieSpaceSquare.wav',
    enemyDieSpaceSusong: './sound/enemyDieSpaceSusong.ogg',
    enemyDieJemulDrill: './sound/enemyDieJemulDrill.wav',
    enemyDieJemulEnergyBolt: './sound/enemyDieJemulEnergyBolt.wav',
    enemyDieJemulHellAir: './sound/enemyDieJemulHellAir.ogg',
    enemyDieJemulHellShip: './sound/enemyDieJemulHellShip.ogg',
    enemyDieJemulRocket: './sound/enemyDieJemulRocket.wav',
    enemyDieJemulSpike: './sound/enemyDieJemulSpike.wav',
    enemyDieJemulBoss: './sound/enemyDieJemulBoss.ogg',
    enemyDieJemulBossEye: './sound/enemyDieJemulBossEye.ogg',
    enemyDieJemulRedJewel: './sound/enemyDieJemulRedJewel.wav',
    enemyDieJemulRedAir: './sound/enemyDieJemulRedAir.wav',
    enemyDieDonggrami: './sound/enemyDieDonggrami.wav',
  }

  static enemyAttack = {
    jemulEnergyBoltAttack: './sound/enemyJemulEnergyBoltAttack.wav',
    jemulHellDrillAttack: './sound/enemyJemulHellDrillAttack.wav',
    jemulBossAttack: './sound/enemyJemulBossAttackLaser.ogg',
    jemulBossAttack2: './sound/enemyJemulBossAttackLaser2.ogg',
    jemulBossAttack3: './sound/enemyJemulBossAttackLaser3.ogg',
  }

  static round = {
    r1_4_message1: './sound/round1_4_message1.ogg',
    r1_4_message2: './sound/round1_4_message2.ogg',
    r1_4_jemulstar: './sound/round1_4_jemulstar.ogg',
    r1_4_jemulstart: './sound/round1_4_jemulstart.ogg',
    r1_4_jemulrun: './sound/round1_4_jemulrun.ogg',
    r2_3_voiceComplete: './sound/round2_3_voiceComplete.ogg',
    r2_3_voiceDraw: './sound/round2_3_voiceDraw.ogg',
    r2_3_voiceFight: './sound/round2_3_voiceFight.ogg',
    r2_3_voiceLose: './sound/round2_3_voiceLose.ogg',
    r2_3_voiceReady: './sound/round2_3_voiceReady.ogg',
    r2_3_voiceStart: './sound/round2_3_voiceStart.ogg',
    r2_3_voiceWin: './sound/round2_3_voiceWin.ogg',
    r2_3_a1_boost: './sound/round2_3_a1_boost.ogg',
    r2_3_a1_damage: './sound/round2_3_a1_damage.ogg',
    r2_3_a1_earthquake: './sound/round2_3_a1_earthquake.ogg',
    r2_3_a1_earthquakeDamage: './sound/round2_3_a1_earthquakeDamage.ogg',
    r2_3_a1_toyHammer: './sound/round2_3_a1_toyHammer.ogg',
    r2_3_a2_break: './sound/round2_3_a2_break.wav',
    r2_3_a2_bomb: './sound/round2_3_a2_bomb.wav',
    r2_3_b2_warp: './sound/round2_3_b2_warp.wav',
    r2_3_c2_squareBlack: './sound/round2_3_c2_squareBlack.wav',
    r2_3_c2_squareRed: './sound/round2_3_c2_squareRed.wav',
    r2_3_c2_squareCyan: './sound/round2_3_c2_squareCyan.wav',
    r2_3_c2_squareLime: './sound/round2_3_c2_squareLime.wav',
    r2_3_c2_squarePink: './sound/round2_3_c2_squarePink.wav'
  }

  static donggrami = {
    exclamationMark: './sound/donggramiExclamationMark.ogg',
    questionMark: './sound/donggramiQuestionMark.ogg',
    emoji: './sound/donggramiImoge.ogg',
    emojiThrow: './sound/donggramiImogeThrow.ogg'
  }

  static music = {
    music01_space_void: './music/music01_space_void.ogg',
    music02_meteorite_zone_field: './music/music02_meteorite_zone_field.ogg',
    music03_meteorite_zone_battle: './music/music03_meteorite_zone_battle.ogg',
    music04_meteorite_zone_red: './music/music04_meteorite_zone_red.ogg',
    music05_space_tour: './music/music05_space_tour.ogg',
    music06_round1_boss_thema: './music/music06_round1_boss_thema.ogg',
    music07_paran_planet_entry: './music/music07_paran_planet_entry.ogg',
    music08_round1_4_jemul: './music/music08_round1_4_jemul.ogg',
    music09_paran_planet: './music/music09_paran_planet.ogg',
    music10_donggrami_maeul: './music/music10_donggrami_maeul.ogg',
    music11A1_battle_room: './music/music11A1_battle_room.ogg',
    music11A2_break_room: './music/music11A2_break_room.ogg',
    music11A3_power_room: './music/music11A3_power_room.ogg',
    music11B1_jump_room: './music/music11B1_jump_room.ogg',
    music11B2_warp_room: './music/music11B2_warp_room.ogg',
    music11B3_move_room: './music/music11B3_move_room.ogg',
    music11C1_bullet_room: './music/music11C1_bullet_room.ogg',
    music11C2_square_room: './music/music11C2_square_room.ogg',
    music11C3_trap_room: './music/music11C3_trap_room.ogg',
  }

  
}
