export class soundSrc {
  static system = {
    systemBack: './sound/systemBack.wav',
    systemBuzzer: './sound/systemBuzzer.wav',
    systemCursor: './sound/systemCursor.wav',
    systemEnter: './sound/systemEnter.ogg',
    systemSelect: './sound/systemSelect.wav',
    systemScore: './sound/systemScore.wav',
    systemLevelUp: './sound/systemLevelUp.wav',
    systemPause: './sound/systemPause.wav',
    systemRoundClear: './sound/systemRoundClear.ogg',
    systemGameOver: './sound/systemGameOver.ogg',
    systemPlayerDamage: './sound/systemPlayerDamage.wav',
    systemPlayerDamageBig: './sound/systemPlayerDamageBig.wav',
    systemPlayerDamageDanger: './sound/systemPlayerDamageDanger.wav',
    systemPlayerDie: './sound/systemPlayerDie.ogg',
    systemSkillSelect: './sound/systemSkillSelect.wav',
  }

  static skill = {
    // baseSkill total count 20
    skillMultyshotUse: './sound/skillMultyshotUse.wav',
    skillMultyshotShot: './sound/skillMultyshotShot.wav',
    skillMissileShot: './sound/skillMissileShot.wav',
    skillMissileHit: './sound/skillMissileHit.wav',
    skillArrowShot: './sound/skillArrow.wav',
    skillLaserShot: './sound/skillLaserShot.ogg',
    skillSapiaWeapon: './sound/skillSapiaWeapon.ogg',
    skillParapoHit: './sound/skillParapoHit.wav',
    skillBlasterShot: './sound/skillBlasterShot.ogg',
    skillSidewaveShot: './sound/skillSidewaveShot.wav',
    skillCriticalChaser: './sound/skillCriticalChaser.ogg',
    skillCriticalChaserHit: './sound/skillCriticalChaserHit.ogg',
    skillHyperBall: './sound/skillHyperBall.wav',
    skillPileBunker: './sound/skillPileBunker.ogg',
    skillPileBunkerHit2: './sound/skillPileBunkerHit2.wav',
    skillPileBunkerHit3: './sound/skillPileBunkerHit3.wav',
    skillSword: './sound/skillSword.ogg',
    skillSwordHit: './sound/skillSwordHit.wav',
    skillSantansu: './sound/skillSantansuHit.ogg',
    skillWhiteflash: './sound/skillWhiteflash.ogg',
    skillRapid: './sound/skillRapid.wav',
    skillSeondanil: './sound/skillSeondanil.ogg',
    skillSeondanilHit: './sound/skillSeondanilHit.wav',
    skillRing: './sound/skillRing.wav',
    skillBoomerang: './sound/skillBoomerang.ogg',
    skillHanjumeok: './sound/skillHanjumeok.ogg',
    skillHanjumeokHit: './sound/skillHanjumeokHit.wav',
    skillHanjumeokSplash: './sound/skillHanjumeokSplash.ogg',
    skillMoon: './sound/skillMoon.ogg',
    skillMoonAttack: './sound/skillMoonAttack.ogg',
  }

  static enemyDie = {
    // space (1-1)
    enemyDieSpaceCar: './sound/enemyDieSpaceCar.wav',
    enemyDieSpaceComet: './sound/enemyDieSpaceComet.wav',
    enemyDieSpaceEnergy: './sound/enemyDieSpaceEnergy.wav',
    enemyDieSpaceGamjigi: './sound/enemyDieSpaceGamjigi.wav',
    enemyDieSpaceLight: './sound/enemyDieSpaceLight.wav',
    enemyDieSpaceRocket: './sound/enemyDieSpaceRocket.wav',
    enemyDieSpaceSmall: './sound/enemyDieSpaceSmall.wav',
    enemyDieSpaceSquare: './sound/enemyDieSpaceSquare.wav',
    enemyDieSpaceSusong: './sound/enemyDieSpaceSusong.ogg',

    // meteorite (1-2)
    enemyDieMeteorite1: './sound/enemyDieMeteorite1.wav',
    enemyDieMeteorite2: './sound/enemyDieMeteorite2.wav',
    enemyDieMeteorite3: './sound/enemyDieMeteorite3.wav',
    enemyDieMeteorite4: './sound/enemyDieMeteorite4.wav',
    enemyDieMeteorite5: './sound/enemyDieMeteorite5.wav',
    enemyDieMeteoriteBomb: './sound/enemyDieMeteoriteBomb.wav',
    enemyDieMeteoriteRed: './sound/enemyDieMeteoriteRed.wav',

    // jemul (1-3)
    enemyDieJemulDrill: './sound/enemyDieJemulDrill.wav',
    enemyDieJemulEnergyBolt: './sound/enemyDieJemulEnergyBolt.wav',
    enemyDieJemulHellAir: './sound/enemyDieJemulHellAir.ogg',
    enemyDieJemulHellShip: './sound/enemyDieJemulHellShip.ogg',
    enemyDieJemulRocket: './sound/enemyDieJemulRocket.wav',
    enemyDieJemulSpike: './sound/enemyDieJemulSpike.wav',
    enemyDieJemulBoss: './sound/enemyDieJemulBoss.ogg',
    enemyDieJemulBossEye: './sound/enemyDieJemulBossEye.ogg',
    enemyDieJemulRedJewel: './sound/enemyDieJemulRedJewel.wav',
    enemyDieJemulRedAir: './sound/enemyDieJemulRedAir.wav',

    // donggrami (2-1)
    enemyDieDonggrami: './sound/enemyDieDonggrami.wav',
    enemyDieDonggramiLeaf: './sound/enemyDieDonggramiLeaf.wav',

    // intruder (2-5)
    enemyDieIntruderJemu: './sound/enemyDieIntruderJemu.ogg',
    enemyDieIntruderSquare: './sound/enemyDieIntruderSquare.ogg',
    enemyDieIntruderDaseok: './sound/enemyDieIntruderDaseok.ogg',
    enemyDieIntruderDiacore: './sound/enemyDieIntruderDiacore.ogg',
    enemyDieIntruderFlying1: './sound/enemyDieIntruderFlying1.ogg',
    enemyDieIntruderFlying2: './sound/enemyDieIntruderFlying2.ogg',
    enemyDieIntruderFlyingRocket: './sound/enemyDieIntruderFlyingRocket.ogg',
    enemyDieIntruderLever: './sound/enemyDieIntruderLever.ogg',
    enemyDieIntruderGami: './sound/enemyDieIntruderGami.ogg',
    enemyDieIntruderHanoi: './sound/enemyDieIntruderHanoi.ogg',
    enemyDieIntruderMetal: './sound/enemyDieIntruderMetal.ogg',
    enemyDieIntruderMomi: './sound/enemyDieIntruderMomi.ogg',
    enemyDieIntruderRendown: './sound/enemyDieIntruderRendown.ogg',

    // tower group 1 (3-1)
    enemyDieTowerBossRobot1: './sound/enemyDieTowerBossRobot1.ogg',
    enemyDieTowerBossCommon: './sound/enemyDieTowerBossCommon.ogg',
    enemyDieTowerDaepo: './sound/enemyDieTowerDaepo.ogg',
    enemyDieTowerMoveBlue: './sound/enemyDieTowerMoveBlue.ogg',
    enemyDieTowerMoveViolet: './sound/enemyDieTowerMoveViolet.ogg',
    enemyDieTowerMoveDarkViolet: './sound/enemyDieTowerMoveDarkViolet.ogg',
    enemyDieTowerMoveYellowEnergy: './sound/enemyDieTowerMoveYellowEnergy.ogg',
    enemyDieTowerDiamond: './sound/enemyDieTowerDiamond.ogg',
    enemyDieTowerGasi: './sound/enemyDieTowerGasi.ogg',
    enemyDieTowerHellba: './sound/enemyDieTowerHellba.ogg',
    enemyDieTowerHellcho: './sound/enemyDieTowerHellcho.ogg',
    enemyDieTowerHellgal: './sound/enemyDieTowerHellgal.ogg',
    enemyDieTowerHellgi: './sound/enemyDieTowerHellgi.ogg',
    enemyDieTowerHelljeon: './sound/enemyDieTowerHelljeon.ogg',
    enemyDieTowerHexagon: './sound/enemyDieTowerHexagon.ogg',
    enemyDieTowerI: './sound/enemyDieTowerI.ogg',
    enemyDieTowerLaserAlpha: './sound/enemyDieTowerLaserAlpha.ogg',
    enemyDieTowerLaserMini: './sound/enemyDieTowerLaserMini.ogg',
    enemyDieTowerOctagon: './sound/enemyDieTowerOctagon.ogg',
    enemyDieTowerPentagon: './sound/enemyDieTowerPentagon.ogg',
    enemyDieTowerPunch: './sound/enemyDieTowerPunch.ogg',
    enemyDieTowerSandglass: './sound/enemyDieTowerSandglass.ogg',
    enemyDieTowerSquare: './sound/enemyDieTowerSquare.ogg',
    enemyDieTowerTapo: './sound/enemyDieTowerTapo.ogg',
    enemyDieTowerX: './sound/enemyDieTowerX.ogg',

    // tower group 2 (3-2)
    enemyDieTowerBar1: './sound/enemyDieTowerBar1.ogg',
    enemyDieTowerBar2: './sound/enemyDieTowerBar2.ogg',
    enemyDieTowerBar3: './sound/enemyDieTowerBar3.ogg',
    enemyDieTowerBossBar: './sound/enemyDieTowerBossBar.ogg',
    enemyDieTowerHellla: './sound/enemyDieTowerHellla.ogg',
    enemyDieTowerHellna: './sound/enemyDieTowerHellna.ogg',
    enemyDieTowerHellpa: './sound/enemyDieTowerHellpa.ogg',
    enemyDieTowerHellpo: './sound/enemyDieTowerHellpo.ogg',
    enemyDieTowerJagijang: './sound/enemyDieTowerJagijang.ogg',
    enemyDieTowerLightning: './sound/enemyDieTowerLightning.ogg',
    enemyDieTowerMagnet: './sound/enemyDieTowerMagnet.ogg',
    enemyDieTowerPentaLight: './sound/enemyDieTowerPentaLight.ogg',
    enemyDieTowerPentaShadow: './sound/enemyDieTowerPentaShadow.ogg',

    // tower group 3 (3-3 ~ 3-4)
    enemyDieTowerBossDasu: './sound/enemyDieTowerBossDasu.ogg',
    enemyDieTowerClockAnalog: './sound/enemyDieTowerClockAnalog.ogg',
    enemyDieTowerClockDigital: './sound/enemyDieTowerClockDigital.ogg',
    enemyDieTowerClockJong: './sound/enemyDieTowerClockJong.ogg',
    enemyDieTowerCore: './sound/enemyDieTowerCore.ogg',
    enemyDieTowerEnergy1: './sound/enemyDieTowerEnergy1.ogg',
    enemyDieTowerEnergy2: './sound/enemyDieTowerEnergy2.ogg',
    enemyDieTowerFakeHell: './sound/enemyDieTowerFakeHell.ogg',
    enemyDieTowerFakeShip: './sound/enemyDieTowerFakeShip.ogg',
    enemyDieTowerShipBig: './sound/enemyDieTowerShipBig.ogg',
    enemyDieTowerShipSmall: './sound/enemyDieTowerShipSmall.ogg',
    enemyDieTowerStar: './sound/enemyDieTowerStar.ogg',

    // tower group 4 (3-5)
    enemyDieTowerNokgasi: './sound/enemyDieTowerNokgasi.ogg'
  }

  static enemyAttack = {
    jemulEnergyBoltAttack: './sound/enemyJemulEnergyBoltAttack.wav',
    jemulHellDrillAttack: './sound/enemyJemulHellDrillAttack.wav',
    jemulBossAttack: './sound/enemyJemulBossAttackLaser.ogg',
    jemulBossAttack2: './sound/enemyJemulBossAttackLaser2.ogg',
    jemulBossAttack3: './sound/enemyJemulBossAttackLaser3.ogg',
    intruderJemuEnergy: './sound/enemyIntruderJemuEnergy.ogg',
    intruderJemuEnergyLow: './sound/enemyIntruderJemuEnergyLow.ogg',
    intruderJemuEnergyHigh: './sound/enemyIntruderJemuEnergyHigh.ogg',
    intruderJemuEnergyPurple: './sound/enemyIntruderJemuEnergyPurple.ogg',
    intruderJemuEnergyReflect: './sound/enemyIntruderJemuEnergyReflect.ogg',
    intruderJemuThunderBig: './sound/enemyIntruderJemuThunderBig.ogg',
    intruderJemuThunderNormal: './sound/enemyIntruderJemuThunderNormal.ogg',
    intruderLeverLaser: './sound/enemyIntruderLeverLaser.ogg',
    intruderRendownMissile: './sound/enemyIntruderRendownMissile.ogg',
    intruderHanoiAttack: './sound/enemyIntruderHanoiAttack.ogg',
    intruderHanoiReflect: './sound/enemyIntruderHanoiReflect.ogg',
    intruderDaseokLaserGreen: './sound/enemyIntruderDaseokLaserGreen.ogg',
    intruderDaseokLaserYellow: './sound/enemyIntruderDaseokLaserYellow.ogg',
    intruderRendownMissileCreate: './sound/enemyIntruderRendownMissileCreate.ogg',
    towerAttackDaepo: './sound/enemyTowerAttackDaepo.ogg',
    towerAttackRocket: './sound/enemyTowerAttackRocket.ogg',
    towerPunchAttack: './sound/enemyTowerPunchAttack.ogg',
    towerHellbaAttack: './sound/enemyTowerHellbaAttack.ogg',
    towerAttackRocketBomb: './sound/enemyTowerAttackRocketBomb.ogg',
    towerLightningAttack: './sound/enemyTowerLightningAttack.ogg',
    towerBossBarAttack: './sound/enemyTowerBossBarAttack.ogg',
    towerJagijangAttack: './sound/enemyTowerJagijangAttack.ogg',
    towerHellpaAttack: './sound/enemyTowerHellpaAttack.ogg',
    towerBarAttack1: './sound/enemyTowerBarAttack1.ogg',
    towerBarAttack2: './sound/enemyTowerBarAttack2.ogg',
    towerBarAttack3: './sound/enemyTowerBarAttack3.ogg',
    towerBossBarCollision: './sound/enemyTowerBossBarCollision.ogg',
    towerBossDasuCoreArrangeMent: './sound/enemyTowerBossDasuCoreArrangeMent.ogg',
    towerBossDasuCoreAttack: './sound/enemyTowerBossDasuCoreAttack.ogg',
    towerBossDasuCoreReflect: './sound/enemyTowerBossDasuCoreReflect.ogg',
    towerBossDasuCoreSummon: './sound/enemyTowerBossDasuCoreSummon.ogg',
    towerClockAttack: './sound/enemyTowerClockAttack.ogg',
    towerClockVibration: './sound/enemyTowerClockVibration.ogg',
    towerCoreSummonBrown: './sound/enemyTowerCoreSummonBrown.ogg',
    towerCoreSummonRainbow: './sound/enemyTowerCoreSummonRainbow.ogg',
    towerFakeBarAttack: './sound/enemyTowerFakeBarAttack.ogg',
    towerShipEquipCore: './sound/enemyTowerShipEquipCore.ogg',
    towerNokgasiAttackOrangePurple: './sound/enemyTowerNokgasiAttackOrangePurple.ogg',
    towerNokgasiAttackGreenGrey: './sound/enemyTowerNokgasiAttackGreenGrey.ogg',
    towerNokgasiAttackPink: './sound/enemyTowerNokgasiAttackPink.ogg',
    towerNokgasiAttackBlue: './sound/enemyTowerNokgasiAttackBlue.ogg',
    towerNokgasiGasiBottom: './sound/enemyTowerNokgasiGasiBottom.ogg',
    towerNokgasiGasiSting: './sound/enemyTowerNokgasiGasiSting.ogg',
    towerNokgasiGasiSpear: './sound/enemyTowerNokgasiGasiSpear.ogg',
    towerNokgasiGasiThrow: './sound/enemyTowerNokgasiGasiThrow.ogg',
    towerNokgasiGasiHyper: './sound/enemyTowerNokgasiGasiHyper.ogg',
    towerNokgasiGasiShot: './sound/enemyTowerNokgasiGasiShot.ogg',
    towerNokgasiGasiPattern5: './sound/enemyTowerNokgasiGasiPattern5.ogg',
    towerAntijemulGravityBall: './sound/enemyTowerAntijemulGravityBall.ogg',
    towerAntijemulGravityBallEffect: './sound/enemyTowerAntijemulGravityBallEffect.ogg',
    towerAntijemulGravityBallFall: './sound/enemyTowerAntijemulGravityBallFall.ogg',
    towerAntijemulRing: './sound/enemyTowerAntijemulRing.ogg',
    towerAntijemulRingBomb: './sound/enemyTowerAntijemulRingBomb.ogg',
    towerAntijemulRingBombEffect: './sound/enemyTowerAntijemulRingBombEffect.ogg',
    towerAntijemulRingRolling: './sound/enemyTowerAntijemulRingRolling.ogg',
    towerAntijemulBackshot: './sound/enemyTowerAntijemulBackshot.ogg',
  }

  static round = {
    r1_4_message1: './sound/round1_4_message1.ogg',
    r1_4_message2: './sound/round1_4_message2.ogg',
    r1_4_jemulstar: './sound/round1_4_jemulstar.ogg',
    r1_4_jemulstart: './sound/round1_4_jemulstart.ogg',
    r1_4_jemulrun: './sound/round1_4_jemulrun.ogg',
    r2_3_voiceComplete: './sound/round2_3_voiceComplete.ogg',
    r2_3_voiceDraw: './sound/round2_3_voiceDraw.ogg',
    r2_3_voiceFight: './sound/round2_3_voiceFight.ogg',
    r2_3_voiceLose: './sound/round2_3_voiceLose.ogg',
    r2_3_voiceReady: './sound/round2_3_voiceReady.ogg',
    r2_3_voiceStart: './sound/round2_3_voiceStart.ogg',
    r2_3_voiceWin: './sound/round2_3_voiceWin.ogg',
    r2_3_a1_boost: './sound/round2_3_a1_boost.ogg',
    r2_3_a1_damage: './sound/round2_3_a1_damage.ogg',
    r2_3_a1_earthquake: './sound/round2_3_a1_earthquake.ogg',
    r2_3_a1_earthquakeDamage: './sound/round2_3_a1_earthquakeDamage.ogg',
    r2_3_a1_toyHammer: './sound/round2_3_a1_toyHammer.ogg',
    r2_3_a2_break: './sound/round2_3_a2_break.ogg',
    r2_3_a2_bomb: './sound/round2_3_a2_bomb.ogg',
    r2_3_b2_warp: './sound/round2_3_b2_warp.ogg',
    r2_3_c2_squareBlack: './sound/round2_3_c2_squareBlack.ogg',
    r2_3_c2_squareRed: './sound/round2_3_c2_squareRed.ogg',
    r2_3_c2_squareCyan: './sound/round2_3_c2_squareCyan.ogg',
    r2_3_c2_squareLime: './sound/round2_3_c2_squareLime.ogg',
    r2_3_c2_squarePink: './sound/round2_3_c2_squarePink.ogg',
    r2_3_a3_power1: './sound/round2_3_a3_power1.ogg',
    r2_3_a3_power2: './sound/round2_3_a3_power2.ogg',
    r2_3_b3_move: './sound/round2_3_b3_move.ogg',
    r2_4_elevatorMove: './sound/round2_4_elevatorMove.ogg',
    r2_4_elevatorDoorOpen: './sound/round2_4_elevatorDoorOpen.wav',
    r2_4_elevatorDoorClose: './sound/round2_4_elevatorDoorClose.wav',
    r2_4_elevatorFloor: './sound/round2_4_elevatorFloor.wav',
    r2_4_message1: './sound/round2_4_message1.ogg',
    r2_5_start: './sound/round2_5_start.ogg',
    r2_5_breakRoom: './sound/round2_5_breakRoom.ogg',
    r3_playerOption: './sound/round3_playerOption.ogg',
    r3_bossWarning: './sound/round3_bossWarning.ogg',
    r3_bossWarningKeyboard: './sound/round3_bossWarningKeyboard.ogg',
    r3_5_phase2Start: './sound/round3_5_phase2Start.ogg',
    r3_5_message1: './sound/round3_5_message1.ogg',
    r3_5_message2: './sound/round3_5_message2.ogg',
    r3_5_message3: './sound/round3_5_message3.ogg',
    r3_5_blackSpaceAreaDie: './sound/round3_5_blackSpaceAreaDie.ogg',
    r3_5_blackSpaceCatch: './sound/round3_5_blackSpaceCatch.ogg',
    r3_5_blackSpaceFind: './sound/round3_5_blackSpaceFind.ogg',
    r3_5_blackSpaceTornado: './sound/round3_5_blackSpaceTornado.ogg',
    r3_5_blackSpaceRed: './sound/round3_5_blackSpaceRed.ogg',
    r3_5_blackSpaceYellowPre: './sound/round3_5_blackSpaceYellowPre.ogg',
    r3_5_blackSpaceYellow: './sound/round3_5_blackSpaceYellow.ogg',
    r3_5_blackSpaceGreen: './sound/round3_5_blackSpaceGreen.ogg',
    r3_5_blackSpaceWarp: './sound/round3_5_blackSpaceWarp.ogg',
  }

  static donggrami = {
    exclamationMark: './sound/donggramiExclamationMark.ogg',
    questionMark: './sound/donggramiQuestionMark.ogg',
    emoji: './sound/donggramiImoge.ogg',
    throw: './sound/donggramithrow.ogg',
    firecracker: './sound/donggramiFirecracker.ogg',
    juiceCola: './sound/donggramiJuiceCola.wav',
    juiceThrow: './sound/donggramiJuiceThrow.wav',
    plate: './sound/donggramiPlate.wav',
    juiceEat: './sound/donggramiJuiceEat.ogg'
  }

  static music = {
    music01_space_void: './music/music01_space_void.ogg',
    music02_meteorite_zone_field: './music/music02_meteorite_zone_field.ogg',
    music03_meteorite_zone_battle: './music/music03_meteorite_zone_battle.ogg',
    music04_meteorite_zone_red: './music/music04_meteorite_zone_red.ogg',
    music05_space_tour: './music/music05_space_tour.ogg',
    music06_round1_boss_thema: './music/music06_round1_boss_thema.ogg',
    music07_paran_planet_entry: './music/music07_paran_planet_entry.ogg',
    music08_round1_4_jemul: './music/music08_round1_4_jemul.ogg',
    music09_paran_planet: './music/music09_paran_planet.ogg',
    music10_donggrami_maeul: './music/music10_donggrami_maeul.ogg',
    music11A1_battle_room: './music/music11A1_battle_room.ogg',
    music11A2_break_room: './music/music11A2_break_room.ogg',
    music11A3_power_room: './music/music11A3_power_room.ogg',
    music11B1_jump_room: './music/music11B1_jump_room.ogg',
    music11B2_warp_room: './music/music11B2_warp_room.ogg',
    music11B3_move_room: './music/music11B3_move_room.ogg',
    music11C1_bullet_room: './music/music11C1_bullet_room.ogg',
    music11C2_square_room: './music/music11C2_square_room.ogg',
    music11C3_trap_room: './music/music11C3_trap_room.ogg',
    music12_donggrami_hall_outside: './music/music12_donggrami_hall_outside.ogg',
    music13_round2_4_jemu: './music/music13_round2_4_jemu.ogg',
    music14_intruder_battle: './music/music14_intruder_battle.ogg',
    music15_donggrami_ruin: './music/music15_donggrami_ruin.ogg',
    music16_down_tower: './music/music16_down_tower.ogg',
    music17_down_tower_boss: './music/music17_down_tower_boss.ogg',
    music18_down_tower_void: './music/music18_down_tower_void.ogg',
    music19_round3_5_phase1: './music/music19_round3_5_phase1.ogg',
    music20_round3_5_blackSpace: './music/music20_round3_5_blackSpace.ogg',
    music21_round3_5_antijemulNormal: './music/music21_round3_5_antijemulNormal.ogg',
    music22_round3_5_antijemulHyper: './music/music22_round3_5_antijemulHyper.ogg',
  }
}
